import Head from "next/head";
import Image from "next/image";
import Accordion from "../components/accordion";
import Carousel from "../components/Carousel";
import Table from "../components/Table";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap"
                    rel="stylesheet"
                />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Some React Components!
                </h1>
                
                <section className={styles.section}>
                    <Table />
                </section>

                <section className={styles.section}>
                    <Carousel />
                </section>

                <section className={styles.section}>
                    <Accordion />
                </section>
                
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/icons/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}
